print("Hello World!")
print("Hello World!")
print("I am learning Python.")
print("It is awesome!")
print("This will work!")
print('This will also work!')
print("Hello World!", end=" ")
print("I will print on the same line.")